export const sampleTasks = [
  {
    title: "Fix regression in payment gateway authorization flow",
    status: "feedback",
    pushTo: "Production",
    reason: "Users reporting intermittent 502 errors during Stripe checkout",
    timeline: "Immediate / Hotfix",
    remark: "High priority blocker affecting EU checkout region",
    date: "2026-08-03",
    user: "Vireak",
    owner: "Dev Team",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  },
  {
    title: "Implement real-time WebSocket connection for execution logs",
    status: "progress",
    pushTo: "Development",
    reason: "Product team requested live streaming of test execution outputs",
    timeline: "Sprint 34 (Aug 15)",
    remark: "Backend socket endpoints deployed to dev cluster",
    date: "2026-08-05",
    user: "QA Tester",
    owner: "Dev Team",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  },
  {
    title: "QA validation for iOS mobile app v2.4.0 release build",
    status: "testing",
    pushTo: "TestFlight",
    reason: "Sanity & regression testing on TestFlight build #142",
    timeline: "Aug 18 Target",
    remark: "Focus area: Biometric authentication & push notifications",
    date: "2026-08-08",
    user: "QA Tester",
    owner: "QA Team",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  },
  {
    title: "UAT sign-off for Enterprise SSO & SAML 2.0 integration",
    status: "success",
    pushTo: "UAT",
    reason: "Stakeholder approval required before production deployment",
    timeline: "Completed Aug 12",
    remark: "All enterprise test cases passed with 100% coverage",
    date: "2026-08-12",
    user: "Vireak",
    owner: "Product Manager",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  },
  {
    title: "Upgrade MongoDB cluster to v8.0 and index optimization",
    status: "done",
    pushTo: "Production",
    reason: "Infrastructure maintenance and database performance tuning",
    timeline: "Completed Aug 10",
    remark: "Query latency reduced by 35%",
    date: "2026-08-10",
    user: "Dev Team",
    owner: "Dev Team",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  },
  {
    title: "Design system component library accessibility audit (WCAG 2.1)",
    status: "backlog",
    pushTo: "Development",
    reason: "Ensure screen reader compatibility for dropdowns & modals",
    timeline: "Sprint 35",
    remark: "Low priority backlog task",
    date: "2026-08-01",
    user: "QA Tester",
    owner: "Vireak",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  },
  {
    title: "Memory leak in background report generation worker",
    status: "feedback",
    pushTo: "Development",
    reason: "Node worker process crashes after running 500+ CSV reports",
    timeline: "Sprint 34",
    remark: "Heap dump analysis points to stream unpipe leak",
    date: "2026-08-15",
    user: "QA Tester",
    owner: "Dev Team",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  },
  {
    title: "Optimize React component re-renders on Kanban drag & drop",
    status: "progress",
    pushTo: "Development",
    reason: "FPS drops when moving cards on large boards",
    timeline: "Aug 20",
    remark: "Memoizing list items & using virtualized arrays",
    date: "2026-08-16",
    user: "Vireak",
    owner: "Dev Team",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  },
  {
    title: "Automated E2E Playwright test suite integration into CI pipeline",
    status: "testing",
    pushTo: "Development",
    reason: "Reduce manual regression testing time per release",
    timeline: "Aug 22",
    remark: "Running against staging environment",
    date: "2026-08-18",
    user: "QA Tester",
    owner: "QA Team",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  },
  {
    title: "Security vulnerability patch for OAuth token refresh logic",
    status: "success",
    pushTo: "Production",
    reason: "Pass third-party penetration testing recommendations",
    timeline: "Aug 14",
    remark: "Verified by security lead",
    date: "2026-08-14",
    user: "Vireak",
    owner: "Vireak",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  },
  {
    title: "Deploy microservices API Gateway v2.5 with rate limiting",
    status: "done",
    pushTo: "Production",
    reason: "Prevent DDoS and API abuse on public endpoints",
    timeline: "Configured Redis token bucket algorithm",
    remark: "Completed Aug 02",
    date: "2026-08-02",
    user: "Dev Team",
    owner: "Dev Team",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  },
  {
    title: "User onboarding tour & interactive guided walkthrough",
    status: "backlog",
    pushTo: "UAT",
    reason: "Improve conversion rate for newly registered QA teams",
    timeline: "Sprint 36",
    remark: "UX wireframes approved",
    date: "2026-08-25",
    user: "Product Manager",
    owner: "QA Team",
    kpiCategory: "none",
    flowType: "none",
    flowValue: ""
  }
];
