import pptxgen from 'pptxgenjs';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';

export const reportExportService = {
  // 1. Export Weekly Standup PowerPoint (.pptx) - REQ-REP-W4 (3-Slide Format)
  exportWeeklyPptx: async ({ startDate, endDate, days, sections, gcin }) => {
    const pptx = new pptxgen();
    pptx.layout = 'LAYOUT_16x9';
    pptx.title = `Weekly QA Operational Standup (${startDate} - ${endDate})`;

    // SLIDE 1: Cover / Team Overview
    const slide1 = pptx.addSlide();
    
    // Background gradient banner
    slide1.addShape(pptx.shapes.RECTANGLE, {
      x: 0, y: 0, w: '100%', h: 1.2,
      fill: { color: '1E293B' }
    });

    slide1.addText('WEEKLY QA OPERATIONAL STANDUP', {
      x: 0.5, y: 0.25, w: 9.0, h: 0.4,
      fontSize: 22, bold: true, color: 'FFFFFF', fontFace: 'Arial'
    });

    slide1.addText(`Cycle Period: ${startDate || 'Mon'} to ${endDate || 'Sat'} | Product Engineering Control Center`, {
      x: 0.5, y: 0.7, w: 9.0, h: 0.3,
      fontSize: 12, color: '94A3B8', fontFace: 'Arial'
    });

    // Summary Metric Cards
    const achievementsCount = sections?.lastWeekAchievement?.length || 0;
    const planCount = sections?.thisWeekPlan?.length || 0;
    const totalCount = (achievementsCount + planCount) || 0;

    // Card 1: Total Cycle Volume
    slide1.addShape(pptx.shapes.RECTANGLE, { x: 0.6, y: 1.8, w: 3.8, h: 2.2, fill: { color: 'F1F5F9' }, line: { color: 'CBD5E1', width: 1 } });
    slide1.addText('TOTAL VOLUME', { x: 0.8, y: 2.0, w: 3.4, h: 0.3, fontSize: 12, bold: true, color: '475569' });
    slide1.addText(String(totalCount), { x: 0.8, y: 2.4, w: 3.4, h: 1.0, fontSize: 44, bold: true, color: '0F172A' });
    slide1.addText('Tasks tracked across Mon - Sat', { x: 0.8, y: 3.5, w: 3.4, h: 0.3, fontSize: 10, color: '64748B' });

    // Card 2: Last Week Achievements
    slide1.addShape(pptx.shapes.RECTANGLE, { x: 4.7, y: 1.8, w: 3.8, h: 2.2, fill: { color: 'ECFDF5' }, line: { color: 'A7F3D0', width: 1 } });
    slide1.addText('ACHIEVEMENTS (DONE)', { x: 4.9, y: 2.0, w: 3.4, h: 0.3, fontSize: 12, bold: true, color: '047857' });
    slide1.addText(String(achievementsCount), { x: 4.9, y: 2.4, w: 3.4, h: 1.0, fontSize: 44, bold: true, color: '065F46' });
    slide1.addText('Resolved & pushed to environment', { x: 4.9, y: 3.5, w: 3.4, h: 0.3, fontSize: 10, color: '059669' });

    // Card 3: Active Cycle Plan
    slide1.addShape(pptx.shapes.RECTANGLE, { x: 8.8, y: 1.8, w: 3.8, h: 2.2, fill: { color: 'EFF6FF' }, line: { color: 'BFDBFE', width: 1 } });
    slide1.addText('ACTIVE PLAN', { x: 9.0, y: 2.0, w: 3.4, h: 0.3, fontSize: 12, bold: true, color: '1D4ED8' });
    slide1.addText(String(planCount), { x: 9.0, y: 2.4, w: 3.4, h: 1.0, fontSize: 44, bold: true, color: '1E40AF' });
    slide1.addText('Tasks in testing, progress, backlog', { x: 9.0, y: 3.5, w: 3.4, h: 0.3, fontSize: 10, color: '2563EB' });

    // Footer note
    slide1.addText('Generated by PECC Automated Reporting Engine', { x: 0.6, y: 5.0, w: 12.0, h: 0.3, fontSize: 10, color: '94A3B8', italic: true });


    // SLIDE 2: Daily Breakdown Table View
    const slide2 = pptx.addSlide();
    slide2.addText('DAILY BREAKDOWN & PARTITIONED STATUS', { x: 0.5, y: 0.3, w: 12.0, h: 0.4, fontSize: 18, bold: true, color: '1E293B' });

    const tableRows = [
      [
        { text: 'Day', options: { bold: true, fill: { color: '1E293B' }, color: 'FFFFFF' } },
        { text: 'Title', options: { bold: true, fill: { color: '1E293B' }, color: 'FFFFFF' } },
        { text: 'Partition Section', options: { bold: true, fill: { color: '1E293B' }, color: 'FFFFFF' } },
        { text: 'Status', options: { bold: true, fill: { color: '1E293B' }, color: 'FFFFFF' } },
        { text: 'Push-To Env', options: { bold: true, fill: { color: '1E293B' }, color: 'FFFFFF' } },
        { text: 'Owner / Remark', options: { bold: true, fill: { color: '1E293B' }, color: 'FFFFFF' } }
      ]
    ];

    const dayKeys = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    dayKeys.forEach(day => {
      const items = days[day] || [];
      items.forEach(item => {
        const isAchievement = ['success', 'done', 'done_production'].includes(item.status);
        const sectionName = isAchievement ? 'Last Week Achievement' : 'This Week Plan';
        tableRows.push([
          { text: day, options: { fontSize: 9 } },
          { text: item.title || '', options: { fontSize: 9, bold: true } },
          { text: sectionName, options: { fontSize: 9, color: isAchievement ? '059669' : '2563EB' } },
          { text: (item.status || '').toUpperCase(), options: { fontSize: 8, bold: true } },
          { text: item.pushTo || 'Development', options: { fontSize: 9 } },
          { text: `${item.owner || 'Unassigned'}${item.remark ? ' - ' + item.remark : ''}`, options: { fontSize: 8 } }
        ]);
      });
    });

    if (tableRows.length === 1) {
      tableRows.push([
        { text: 'Mon-Sat', options: {} },
        { text: 'No task records logged for this cycle', options: {} },
        { text: '-', options: {} },
        { text: '-', options: {} },
        { text: '-', options: {} },
        { text: '-', options: {} }
      ]);
    }

    slide2.addTable(tableRows.slice(0, 14), {
      x: 0.5, y: 0.9, w: 12.3,
      colW: [1.1, 4.0, 2.2, 1.3, 1.4, 2.3],
      fontSize: 9,
      border: { pt: 0.5, color: 'E2E8F0' }
    });


    // SLIDE 3: GCIN Matrix (Good, Challenge, Improvement, Next Action)
    const slide3 = pptx.addSlide();
    slide3.addText('GCIN MATRIX (Good, Challenge, Improvement, Next Action)', { x: 0.5, y: 0.3, w: 12.0, h: 0.4, fontSize: 18, bold: true, color: '1E293B' });

    const createGcinBox = (title, items, x, y, w, h, bg, border, titleColor) => {
      slide3.addShape(pptx.shapes.RECTANGLE, { x, y, w, h, fill: { color: bg }, line: { color: border, width: 1 } });
      slide3.addText(title, { x: x + 0.2, y: y + 0.15, w: w - 0.4, h: 0.3, fontSize: 13, bold: true, color: titleColor });
      const bulletText = (items && items.length > 0)
        ? items.map(it => `• ${it}`).join('\n')
        : '• No specific entries recorded';
      slide3.addText(bulletText, { x: x + 0.2, y: y + 0.5, w: w - 0.4, h: h - 0.6, fontSize: 10, color: '334155', valign: 'top' });
    };

    // Grid layout for 4 GCIN sections
    createGcinBox('GOOD (Accomplishments)', gcin?.good, 0.5, 0.9, 6.0, 2.3, 'ECFDF5', 'A7F3D0', '047857');
    createGcinBox('CHALLENGE (Blockers & >48h Feedback)', gcin?.challenge, 6.8, 0.9, 6.0, 2.3, 'FEF2F2', 'FECACA', 'B91C1C');
    createGcinBox('IMPROVEMENT (Action Items)', gcin?.improvement, 0.5, 3.4, 6.0, 2.3, 'EFF6FF', 'BFDBFE', '1D4ED8');
    createGcinBox('NEXT ACTION (Target Deliverables)', gcin?.nextAction, 6.8, 3.4, 6.0, 2.3, 'F5F3FF', 'DDD6FE', '6D28D9');

    await pptx.writeFile({ fileName: `Weekly_QA_Standup_${startDate}_to_${endDate}.pptx` });
  },

  // 2. Export Monthly KPI Report PDF (.pdf) - REQ-REP-M4
  exportMonthlyPdf: async ({ targetMonth, owner, kpiTargets, counts, performanceTiers, timelinessSummary, challengesSuccess }) => {
    const doc = new jsPDF('p', 'mm', 'a4');

    // Header Color Block
    doc.setFillColor(30, 41, 59); // Slate-800
    doc.rect(0, 0, 210, 28, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('MONTHLY INDIVIDUAL KPI PERFORMANCE REPORT', 14, 12);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`Evaluation Period: ${targetMonth}  |  Owner: ${owner || 'All QA Engineers'}`, 14, 20);
    doc.text(`PECC Control Center`, 160, 20);

    // Section I: IMP Goal Target Evaluation (REQ-REP-M1 & REQ-REP-M2)
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Section I: IMP KPI Target Evaluation & Performance Tier', 14, 36);

    const kpiRows = [
      [
        'Quick Test on TestFlight',
        `${counts?.quick_test || 0} tasks`,
        `Good ≥ ${kpiTargets?.quick_test?.good || 3}, Excellence ≥ ${kpiTargets?.quick_test?.excellence || 4}`,
        performanceTiers?.quick_test || 'Good'
      ],
      [
        'Finding Product Error',
        `${counts?.finding_error || 0} errors`,
        `Good ≥ ${kpiTargets?.finding_error?.good || 4}, Excellence ≥ ${kpiTargets?.finding_error?.excellence || 6}`,
        performanceTiers?.finding_error || 'Good'
      ],
      [
        'Conduct Testing New Feature',
        `${counts?.conduct_testing || 0} features`,
        `Good ≥ ${kpiTargets?.conduct_testing?.good || 4}, Excellence ≥ ${kpiTargets?.conduct_testing?.excellence || 6}`,
        performanceTiers?.conduct_testing || 'Good'
      ],
      [
        'New Idea Propose',
        `${counts?.new_idea || 0} proposals`,
        `Good ≥ ${kpiTargets?.new_idea?.good || 1}, Excellence ≥ ${kpiTargets?.new_idea?.excellence || 3}`,
        performanceTiers?.new_idea || 'Good'
      ],
      [
        'Research Testing Template',
        `${counts?.research_doc || 0} docs`,
        `Good ≥ ${kpiTargets?.research_doc?.good || 1}, Excellence ≥ ${kpiTargets?.research_doc?.excellence || 2}`,
        performanceTiers?.research_doc || 'Good'
      ]
    ];

    doc.autoTable({
      startY: 40,
      head: [['KPI Category', 'Achieved Volume', 'Dynamic Target Threshold', 'Assigned Tier']],
      body: kpiRows,
      theme: 'grid',
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold' },
      styles: { fontSize: 9, cellPadding: 3 }
    });

    let currentY = doc.lastAutoTable.finalY + 10;

    // Overall Tier Box
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(14, currentY, 182, 14, 2, 2, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.text(`Overall Assigned Performance Tier: ${performanceTiers?.overall || 'Good'}`, 18, currentY + 9);

    currentY += 22;

    // Section II: Timeliness & Deadline Auditing (REQ-REP-M3)
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Section II: Delivery Timeliness Breakdown', 14, currentY);

    currentY += 4;

    const timelinessRows = [
      ['Completed On Time', `${timelinessSummary?.onTimeCount || 0} tasks`, 'Delivered on or before target timeline date'],
      ['Overdeadline', `${timelinessSummary?.overDeadlineCount || 0} tasks`, 'Completed after deadline (requires delay reason logging)']
    ];

    doc.autoTable({
      startY: currentY,
      head: [['Category', 'Task Count', 'Audit Description']],
      body: timelinessRows,
      theme: 'striped',
      headStyles: { fillColor: [71, 85, 105], textColor: [255, 255, 255] },
      styles: { fontSize: 9 }
    });

    currentY = doc.lastAutoTable.finalY + 10;

    // Itemized Overdeadline Table if any
    if (timelinessSummary?.overDeadlineItems && timelinessSummary.overDeadlineItems.length > 0) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Overdeadline Task Items & Mandatory Delay Attribution:', 14, currentY);
      currentY += 4;

      const overRows = timelinessSummary.overDeadlineItems.map(item => [
        item.title || '',
        item.date || '-',
        item.due_date || item.timeline || '-',
        item.delayReason || item.reason || 'Requirement change'
      ]);

      doc.autoTable({
        startY: currentY,
        head: [['Task Title', 'Completion Date', 'Target Date', 'Attributed Delay Reason']],
        body: overRows,
        theme: 'grid',
        headStyles: { fillColor: [185, 28, 28], textColor: [255, 255, 255] },
        styles: { fontSize: 8, cellPadding: 2 }
      });
      currentY = doc.lastAutoTable.finalY + 10;
    }

    // Section III: Monthly Challenges & Success Stories
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Section III: Monthly Challenges & Success Highlights', 14, currentY);
    currentY += 6;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const challengesText = challengesSuccess?.challenges || 'No major challenges recorded.';
    const successText = challengesSuccess?.successStories || 'Delivered key QA milestones on time.';

    doc.text(`• Challenges Encountered: ${challengesText}`, 14, currentY, { maxWidth: 180 });
    currentY += 12;
    doc.text(`• Success Highlights: ${successText}`, 14, currentY, { maxWidth: 180 });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Report ID: REP-${targetMonth}-${Date.now().toString().slice(-4)}  |  Locked & Verified by PECC Engine`, 14, 285);

    doc.save(`Monthly_KPI_Report_${owner || 'Individual'}_${targetMonth}.pdf`);
  },

  // 3. Export XLSX Spreadsheet
  exportToXlsx: ({ filename, sheets }) => {
    const wb = XLSX.utils.book_new();
    sheets.forEach(s => {
      const ws = XLSX.utils.json_to_sheet(s.data);
      XLSX.utils.book_append_sheet(wb, ws, s.name || 'Sheet1');
    });
    XLSX.writeFile(wb, `${filename}.xlsx`);
  }
};
